### PR TITLE
Minor improvement to readability

### PR DESCRIPTION
**Pull request by Aareon**
Make conditionals a bit more Pythonic. I'll be back for this one.

### CODE REVIEW

**Comment by hclivess** [comment]
Definitely more pythonic, I will test this and merge. Thank you.

**Comment by SpoopySaitama** [comment]
Be cautious when doing this. Both `False` and `None` will satisfy the conditionals now.

**Comment by unazed** [comment]
Yes you shouldn't edit code to make it more ambiguous, I would suggest rewriting the code to 

```py
if <variable> is None:
    <code>
```

**Comment by hclivess** [comment]
Thanks, I was just thinking about doing it this way.

**Comment by Aareon** [comment]
Thanks unazed and spoopy

**Pull request merged**
