### PR TITLE
Update geo.py

### PR DESCRIPTION
**Pull request by Aareon**
Just making some improvements. I don't really see the need to create and append to a list as many times as was previously done. A docstring is useful in this case, and can be formatted like any other string.

### CODE REVIEW

**Comment by hclivess** [comment]
Hi, getting this:

  File "C:/Users/Meegopad/PycharmProjects/Bismuth/markers/geo.py", line 26, in get
    print("IPs:", ips)
NameError: name 'ips' is not defined

**Comment by Aareon** [comment]
Ah, simple fix. I'm going to be adding one or two more commits, so don't merge just yet, I'll let you know when I'm done.

**Comment by Aareon** [comment]
@hclivess can you give an example output from
```
s = socks.socksocket()
        s.settimeout(10)
        s.connect(("127.0.0.1", 5658))
        connections.send(s, "statusget", 10)
        response = connections.receive(s, 10)
        s.close()
```
Thanks!

**Comment by hclivess** [comment]
Hi, these responses are available to see in node.py and commands.py can be used to extract those responses

**Comment by Aareon** [comment]
Commits are slow because my PC is inop right now. Coding on mobile is tedious

**Comment by Aareon** [comment]
@hclivess having some real issues with the `Crypto` library. After having done `py -m pip install crypto`, not `Random` or `Crypto.PublicKey` wants to import. Have I installed the wrong module? Can we maybe put a `requirements.txt` on the to-do list?

**Comment by Aareon** [comment]
Apparently the module is `pycrypto`

**Comment by EggPool** [comment]
Module is pycryptodome, it's in the existing requirements.txt

**Comment by Aareon** [comment]
Ah, I failed to find it on my first look through. I do see it now. Thanks for clearing that up

**Comment by EggPool** [comment]
About socks/sockets/requests: bismuth node uses a custom protocol, based upon raw sockets (and optionally a tor proxy), it's not json-rpc over http like btc and derivatives. So you can't simply use requests.
Best is to keep the default connections.py module to have some global coherence.

**Comment by Aareon** [comment]
It would seem even after having installed the correct module, I still can't import any of the `Crypto` stuff.

**Comment by Aareon** [comment]
And I'll keep that in mind. Maybe I'll just clean it up if I can

**Comment by Aareon** [comment]
I think I might work on getting some `SQLAlchemy` action going on. That'll be a **huge** improvement, and would require some help from just about everyone, really.

**Comment by Aareon** [comment]
Also, having some issues finding the execution entry point. If I wanted to start the wallet, would I execute `wallet.py`?

**Comment by EggPool** [comment]
Don't spent time on node.py or connections.py for now: there is major work undergoing with the connections and protocol, as well as modularizing the node code (and getting rid of globals). This will change.
Once modular, then specific parts of the code (like sql , connections, peers...) would be easier to work on. 

Yes, (light) wallet is wallet.py , it connects to a node (light_ip in config)

**Comment by Aareon** [comment]
So if you were to have me focus on one thing, what would that be?

**Comment by EggPool** [comment]
Well, this PR is "Geo.py", I thought it was what you were working on :)

You may come to the #dev slack channel, easier to chat than via comments.
I'm just one dev helping, not one of the core devs, you'll find them there, too.

**Comment by Aareon** [comment]
Alright, I'll be joining back here shortly

**Comment by Aareon** [comment]
Is it bismuth.slack.com?

**Comment by Aareon** [comment]
Oh, I need my account re-activated. It's `Aareon` with a snake emoji I believe

**Comment by Aareon** [comment]
@hclivess @EggPool

**Comment by hclivess** [comment]
Is the work done here?

**Comment by Aareon** [comment]
I’m actually going to close this PR, and recommit what I did in `geo.py` as soon as I get a chance. I got a little off task in here. I decided to contribute a little differently from now on.

**Pull request closed without merging**
