### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by Aareon**
This PR is intended to update `node.py` so that we use context managers wherever feasible, make minor readability changes, so on and so forth. Please let me know if you have any qualms with this PR.

This PR supersedes https://github.com/hclivess/Bismuth/pull/299

### CODE REVIEW

**Comment by EggPool** [comment]
Agreed with most of the changes.
Just one warning, `text_factory = str` is removed everywhere:
Some places it has no reason to be there (when only deleting rows, no matter what the factory is)
But it has to stay defined for general purpose db handlers like index_define(), db_h_define() aso.

**Comment by hclivess** [comment]
Agreed, text_factory str requires different handling of data according to this:
https://docs.python.org/2/library/sqlite3.html#sqlite3.Connection.text_factory

Can you please restore them and resubmit the PR?

**Comment by Aareon** [comment]
Absolutely. I'll take care of this. I won't need to resubmit the PR, per se, but I will commit to my branch so that it appears here. @EggPool @hclivess

**Comment by hclivess** [comment]
Merging for testing, thank you!

**Pull request merged**
