### PR TITLE
Update anon_dappie.py

### PR DESCRIPTION
**Pull request by Aareon**

### CODE REVIEW

**Comment by Aareon** [comment]
This PR might be a little pedantic. I do believe that there are some notes to be taken here, but as far as I’m concerned, you can take it or leave it.

**Comment by hclivess** [comment]
for some reason it shows there is a conflict in github, do you know how to resolve it (I have no experince in that)

**Comment by Aareon** [comment]
@hclivess done

**Comment by hclivess** [comment]
Good catch, thanks. Not really keeping track with all the apps

**Pull request merged**
